# Generated by Django 4.2.7 on 2026-01-22 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("kelas", models.CharField(max_length=20)),
                ("tanggal", models.DateField()),
                ("mata_pelajaran", models.CharField(max_length=100)),
                ("data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attendance_draft",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("waktu", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=50)),
                ("keterangan", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nisn",
                    models.ForeignKey(
                        db_column="nisn",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
                "indexes": [
                    models.Index(fields=["nisn"], name="attendance_nisn_862ac6_idx"),
                    models.Index(
                        fields=["tanggal"], name="attendance_tanggal_53415e_idx"
                    ),
                ],
            },
        ),
    ]
