# Generated by Django 5.2.10 on 2026-02-07 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_add_jam_pelajaran"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["tanggal", "jam_ke", "nisn"]},
        ),
        migrations.RenameIndex(
            model_name="attendance",
            new_name="attendance_jam_ke_7612b4_idx",
            old_name="attendance_jam_ke_idx",
        ),
    ]
