# Generated by Django 5.2.10 on 2026-04-19 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='capaian_pembelajaran',
            field=models.TextField(blank=True, help_text='Capaian pembelajaran yang dicapai pada sesi ini', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='catatan',
            field=models.TextField(blank=True, help_text='Catatan tambahan dari guru', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='guru_pengganti',
            field=models.ForeignKey(blank=True, help_text="Diisi jika tipe_pengajar='guru_pengganti'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_as_pengganti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='materi',
            field=models.CharField(blank=True, help_text='Materi yang diajarkan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='tipe_pengajar',
            field=models.CharField(choices=[('guru_asli', 'Guru Asli'), ('guru_pengganti', 'Guru Pengganti')], default='guru_asli', help_text='Apakah yang mengajar guru asli atau pengganti', max_length=20),
        ),
    ]
