# Generated by Django 5.2.10 on 2026-04-20 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_add_teaching_detail_fields'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TitipanTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(max_length=20)),
                ('mata_pelajaran', models.CharField(max_length=100)),
                ('tanggal_berlaku', models.DateField(help_text='Tanggal tugas harus dikerjakan')),
                ('deskripsi_tugas', models.TextField()),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('dikerjakan', 'Dikerjakan')], default='menunggu', max_length=20)),
                ('catatan_piket', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(help_text='Guru yang menitipkan tugas', on_delete=django.db.models.deletion.CASCADE, related_name='titipan_tugas', to=settings.AUTH_USER_MODEL)),
                ('guru_piket', models.ForeignKey(blank=True, help_text='Guru piket yang mengerjakan tugas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tugas_dikerjakan', to=settings.AUTH_USER_MODEL)),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tahunajaran')),
            ],
            options={
                'verbose_name': 'Titipan Tugas',
                'verbose_name_plural': 'Titipan Tugas',
                'db_table': 'titipan_tugas',
                'ordering': ['tanggal_berlaku', 'kelas'],
            },
        ),
    ]
