# Generated by Django 5.2.10 on 2026-04-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_add_titipan_tugas'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ada_penilaian',
            field=models.BooleanField(default=False, help_text='Tandai jika sesi ini ada penilaian yang perlu diinput'),
        ),
        migrations.AddField(
            model_name='titipantugas',
            name='jam_ke',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Jam pelajaran ke berapa (opsional)', null=True),
        ),
    ]
