# Generated by Django 4.2.29 on 2026-04-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_add_titipan_tugas"),
    ]

    operations = [
        migrations.AddField(
            model_name="titipantugas",
            name="jam_ke",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Jam pelajaran ke berapa (opsional)", null=True
            ),
        ),
    ]
