# Generated by Django 5.2.10 on 2026-04-26 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_add_ada_penilaian_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ketuntasan_materi',
            field=models.IntegerField(default=0, help_text='Persentase ketuntasan materi (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
