# Generated by Django 4.2.29 on 2026-04-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_titipantugas_jam_ke"),
        ("attendance", "0007_add_ketuntasan_materi"),
    ]

    operations = []
