# Generated by Django 4.2.29 on 2026-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_merge_20260426_2057"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="tujuan_pembelajaran",
            field=models.TextField(
                blank=True,
                help_text="Tujuan pembelajaran yang ingin dicapai pada sesi ini",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="tipe_pengajar",
            field=models.CharField(
                choices=[
                    ("guru_pengampu", "Guru Pengampu"),
                    ("guru_piket", "Guru Piket"),
                ],
                default="guru_pengampu",
                help_text="Apakah yang mengajar guru pengampu atau guru piket",
                max_length=20,
            ),
        ),
    ]
