# Generated by Django 4.2.29 on 2026-04-28 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0009_attendance_tujuan_pembelajaran_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="input_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User yang menginput data attendance ini",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_inputs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["input_by"], name="attendance_input_b_eb3dbb_idx"
            ),
        ),
    ]
