# Generated by Django 5.2.10 on 2026-03-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TahunAjaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        help_text="Format: YYYY/YYYY (contoh: 2025/2026)",
                        max_length=20,
                        verbose_name="Tahun Ajaran",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("Ganjil", "Ganjil"), ("Genap", "Genap")],
                        max_length=10,
                        verbose_name="Semester",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Tandai sebagai tahun ajaran aktif",
                        verbose_name="Aktif",
                    ),
                ),
                (
                    "tanggal_mulai",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Mulai"
                    ),
                ),
                (
                    "tanggal_selesai",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Selesai"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tahun Ajaran",
                "verbose_name_plural": "Tahun Ajaran",
                "ordering": ["-nama", "-semester"],
                "unique_together": {("nama", "semester")},
            },
        ),
    ]
