# Generated by Django 5.2.10 on 2026-04-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterJam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesi', models.CharField(choices=[('tahfidz', 'Tahfidz'), ('kbm', 'KBM'), ('diniyah', 'Diniyah')], max_length=20, verbose_name='Sesi')),
                ('jam_ke', models.IntegerField(verbose_name='Jam Ke')),
                ('jam_mulai', models.TimeField(verbose_name='Jam Mulai')),
                ('jam_selesai', models.TimeField(verbose_name='Jam Selesai')),
                ('keterangan', models.CharField(blank=True, max_length=100, verbose_name='Keterangan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Jam',
                'verbose_name_plural': 'Master Jam',
                'ordering': ['sesi', 'jam_ke'],
                'unique_together': {('sesi', 'jam_ke')},
            },
        ),
    ]
