# Generated by Django 5.2.10 on 2026-04-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_master_jam'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Mata Pelajaran')),
                ('kode', models.CharField(blank=True, help_text='Singkatan/kode mapel (opsional)', max_length=20, verbose_name='Kode')),
                ('sesi', models.CharField(blank=True, choices=[('', '-'), ('kbm', 'KBM'), ('diniyah', 'Diniyah'), ('tahfidz', 'Tahfidz')], default='', help_text='Sesi dimana mapel ini diajarkan (kosong = semua)', max_length=20, verbose_name='Sesi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Mata Pelajaran',
                'verbose_name_plural': 'Master Mata Pelajaran',
                'ordering': ['sesi', 'nama'],
            },
        ),
    ]
