# Generated by Django 5.2.10 on 2026-04-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_master_mapel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermapel',
            name='nama',
            field=models.CharField(max_length=100, verbose_name='Nama Mata Pelajaran'),
        ),
        migrations.AlterField(
            model_name='mastermapel',
            name='sesi',
            field=models.CharField(choices=[('kbm', 'KBM'), ('diniyah', 'Diniyah'), ('tahfidz', 'Tahfidz')], max_length=20, verbose_name='Sesi'),
        ),
        migrations.AlterUniqueTogether(
            name='mastermapel',
            unique_together={('nama', 'sesi')},
        ),
    ]
