
# Generated by Django 5.2.10 on 2026-01-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="aktif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="current_hafalan",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="tanggal_masuk",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="target_hafalan",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="target_nilai",
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name="student",
            name="wali_nama",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="wali_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["nisn"], name="students_nisn_10ad59_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["nama"], name="students_nama_ed8a9a_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["kelas"], name="students_kelas_70284b_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["program"], name="students_program_c510a3_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["aktif"], name="students_aktif_5ac07a_idx"),
        ),
    ]
