# Generated by Django 5.2.10 on 2026-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "students",
            "0002_student_aktif_student_current_hafalan_student_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="alamat",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="alasan_keluar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="catatan_alumni",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="ijazah_diterima",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="jenis_kelamin",
            field=models.CharField(
                blank=True,
                choices=[("L", "Laki-laki"), ("P", "Perempuan")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("aktif", "Aktif"),
                    ("alumni", "Alumni"),
                    ("pindah", "Pindah"),
                    ("dikeluarkan", "Dikeluarkan"),
                ],
                default="aktif",
                help_text="Status santri (aktif/alumni/pindah/dikeluarkan)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="tahun_lulus",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="tanggal_keluar",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="tanggal_lahir",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="tempat_lahir",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="wali_hubungan",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="wali_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["status"], name="students_status_3ac771_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["tahun_lulus"], name="students_tahun_l_55efa5_idx"
            ),
        ),
    ]
