# Generated by Django 5.2.10 on 2026-04-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0004_clean_kelas_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['hari', 'jam_ke', 'jam_mulai']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='jam_ke',
            field=models.IntegerField(blank=True, help_text='Jam pelajaran ke-N (1-10)', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='jam_mulai',
            field=models.TimeField(blank=True, help_text='Waktu mulai pelajaran', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='jam_selesai',
            field=models.TimeField(blank=True, help_text='Waktu selesai pelajaran', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, help_text='Tahun ajaran jadwal ini berlaku', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.tahunajaran'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hari',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='jam',
            field=models.CharField(blank=True, help_text='Legacy: format bebas jam', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='username',
            field=models.CharField(help_text='Username guru', max_length=50),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['username', 'hari'], name='idx_schedule_user_hari'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['kelas', 'hari'], name='idx_schedule_kelas_hari'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['tahun_ajaran', 'semester'], name='idx_schedule_periode'),
        ),
    ]
