# Generated by Django 5.2.10 on 2026-04-26 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_master_jam'),
        ('students', '0005_add_schedule_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='master_jam',
            field=models.ForeignKey(blank=True, help_text='Referensi ke master jam (otomatis isi jam_ke, jam_mulai, jam_selesai)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.masterjam'),
        ),
    ]
