# Generated by Django 5.2.10 on 2026-04-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_master_jam_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='catatan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='nis',
            field=models.CharField(help_text='Nomor Induk Siswa lokal (7 digit, misal: 0000664)', max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['nis'], name='students_nis_e8be98_idx'),
        ),
    ]
