# Generated by Django 5.2.10 on 2026-05-01 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_master_mapel_unique'),
        ('students', '0007_student_catatan_student_nis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='jam_ke_akhir',
            field=models.IntegerField(blank=True, help_text='Jam pelajaran akhir (jika rentang, misal jam 1-3 maka ini = 3)', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='jam_selesai_akhir',
            field=models.TimeField(blank=True, help_text='Waktu selesai akhir (dari master_jam_akhir)', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='master_jam_akhir',
            field=models.ForeignKey(blank=True, help_text='Master jam akhir untuk rentang (opsional, jika lebih dari 1 jam)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_akhir', to='core.masterjam'),
        ),
    ]
