# Generated by Django 5.2.10 on 2026-03-05 00:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "students",
            "0002_student_aktif_student_current_hafalan_student_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Halaqoh",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nama",
                    models.CharField(
                        help_text="Nama halaqoh, misal: Halaqoh Tahfidz A",
                        max_length=100,
                    ),
                ),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("tahfidz", "Tahfidz"),
                            ("tahsin", "Tahsin"),
                            ("kajian", "Kajian Kitab"),
                            ("bahasa", "Bahasa Arab/Inggris"),
                        ],
                        default="tahfidz",
                        max_length=20,
                    ),
                ),
                (
                    "musyrif",
                    models.CharField(
                        help_text="Nama ustadz/musyrif pembimbing", max_length=100
                    ),
                ),
                (
                    "musyrif_username",
                    models.CharField(
                        blank=True,
                        help_text="Username musyrif di sistem",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "jadwal",
                    models.CharField(
                        blank=True,
                        help_text="Jadwal halaqoh, misal: Senin-Kamis 05:00-06:00",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "lokasi",
                    models.CharField(
                        blank=True,
                        help_text="Lokasi halaqoh",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "kapasitas",
                    models.PositiveIntegerField(
                        default=15, help_text="Maksimal anggota halaqoh"
                    ),
                ),
                ("aktif", models.BooleanField(default=True)),
                (
                    "tahun_ajaran",
                    models.CharField(help_text="Format: 2025/2026", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Halaqoh",
                "verbose_name_plural": "Halaqoh",
                "db_table": "kesantrian_halaqoh",
                "ordering": ["jenis", "nama"],
            },
        ),
        migrations.CreateModel(
            name="HalaqohMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tanggal_gabung", models.DateField(auto_now_add=True)),
                ("aktif", models.BooleanField(default=True)),
                ("catatan", models.TextField(blank=True, null=True)),
                (
                    "halaqoh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anggota",
                        to="kesantrian.halaqoh",
                    ),
                ),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="halaqoh_membership",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anggota Halaqoh",
                "verbose_name_plural": "Anggota Halaqoh",
                "db_table": "kesantrian_halaqoh_member",
                "unique_together": {("halaqoh", "siswa")},
            },
        ),
        migrations.CreateModel(
            name="Ibadah",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tanggal", models.DateField(help_text="Tanggal pelaksanaan ibadah")),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("sholat_wajib", "Sholat Wajib"),
                            ("sholat_sunnah", "Sholat Sunnah"),
                            ("puasa", "Puasa"),
                            ("dzikir", "Dzikir/Wirid"),
                            ("tilawah", "Tilawah Al-Quran"),
                        ],
                        help_text="Jenis ibadah",
                        max_length=20,
                    ),
                ),
                (
                    "waktu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("subuh", "Subuh"),
                            ("dzuhur", "Dzuhur"),
                            ("ashar", "Ashar"),
                            ("maghrib", "Maghrib"),
                            ("isya", "Isya"),
                            ("dhuha", "Dhuha"),
                            ("tahajud", "Tahajud"),
                            ("rawatib_qabliyah", "Rawatib Qabliyah"),
                            ("rawatib_badiyah", "Rawatib Ba'diyah"),
                            ("witir", "Witir"),
                            ("tarawih", "Tarawih"),
                        ],
                        help_text="Waktu sholat (untuk jenis sholat)",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("hadir", "Hadir/Terlaksana"),
                            ("tidak_hadir", "Tidak Hadir"),
                            ("terlambat", "Terlambat"),
                            ("izin", "Izin"),
                            ("sakit", "Sakit"),
                        ],
                        default="hadir",
                        max_length=20,
                    ),
                ),
                (
                    "catatan",
                    models.TextField(
                        blank=True, help_text="Catatan tambahan", null=True
                    ),
                ),
                (
                    "pencatat",
                    models.CharField(
                        help_text="Username musyrif/guru yang mencatat", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "siswa",
                    models.ForeignKey(
                        help_text="Santri yang dicatat ibadahnya",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ibadah_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ibadah",
                "verbose_name_plural": "Ibadah",
                "db_table": "kesantrian_ibadah",
                "ordering": ["-tanggal", "waktu"],
                "indexes": [
                    models.Index(
                        fields=["siswa", "tanggal"],
                        name="kesantrian__siswa_i_a89039_idx",
                    ),
                    models.Index(
                        fields=["tanggal", "jenis"],
                        name="kesantrian__tanggal_18187c_idx",
                    ),
                    models.Index(
                        fields=["jenis", "waktu"], name="kesantrian__jenis_5b6659_idx"
                    ),
                ],
                "unique_together": {("siswa", "tanggal", "jenis", "waktu")},
            },
        ),
        migrations.CreateModel(
            name="Pembinaan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tanggal", models.DateField()),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("hafalan", "Progress Hafalan"),
                            ("akhlak", "Pembinaan Akhlak"),
                            ("kedisiplinan", "Kedisiplinan"),
                            ("akademik", "Akademik Keagamaan"),
                            ("kesehatan", "Kesehatan"),
                            ("sosial", "Interaksi Sosial"),
                            ("bakat", "Pengembangan Bakat"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "judul",
                    models.CharField(
                        help_text="Judul/ringkasan pembinaan", max_length=200
                    ),
                ),
                ("deskripsi", models.TextField(help_text="Deskripsi lengkap")),
                (
                    "tingkat",
                    models.CharField(
                        choices=[
                            ("sangat_baik", "Sangat Baik"),
                            ("baik", "Baik"),
                            ("cukup", "Cukup"),
                            ("perlu_perhatian", "Perlu Perhatian"),
                            ("perlu_pembinaan", "Perlu Pembinaan Khusus"),
                        ],
                        default="baik",
                        max_length=20,
                    ),
                ),
                (
                    "tindak_lanjut",
                    models.TextField(
                        blank=True, help_text="Rekomendasi tindak lanjut", null=True
                    ),
                ),
                (
                    "pembina",
                    models.CharField(help_text="Nama pembina/musyrif", max_length=100),
                ),
                (
                    "pembina_username",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "surah",
                    models.CharField(
                        blank=True,
                        help_text="Nama surah (untuk kategori hafalan)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("ayat_mulai", models.PositiveIntegerField(blank=True, null=True)),
                ("ayat_selesai", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "jumlah_halaman",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Jumlah halaman yang dihafal/dimurojaah",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pembinaan_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pembinaan",
                "verbose_name_plural": "Pembinaan",
                "db_table": "kesantrian_pembinaan",
                "ordering": ["-tanggal", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["siswa", "tanggal"],
                        name="kesantrian__siswa_i_15e9c4_idx",
                    ),
                    models.Index(
                        fields=["kategori"], name="kesantrian__kategor_fb4582_idx"
                    ),
                    models.Index(
                        fields=["tingkat"], name="kesantrian__tingkat_18f00c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TargetHafalan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "semester",
                    models.CharField(
                        choices=[("Ganjil", "Ganjil"), ("Genap", "Genap")],
                        max_length=10,
                    ),
                ),
                ("tahun_ajaran", models.CharField(max_length=10)),
                (
                    "target_juz",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target hafalan dalam juz",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "tercapai_juz",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hafalan yang sudah tercapai",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                ("catatan", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_hafalan_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Target Hafalan",
                "verbose_name_plural": "Target Hafalan",
                "db_table": "kesantrian_target_hafalan",
                "unique_together": {("siswa", "semester", "tahun_ajaran")},
            },
        ),
    ]
