# Generated by Django 5.2.10 on 2026-03-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kesantrian", "0001_initial_kesantrian"),
        (
            "students",
            "0002_student_aktif_student_current_hafalan_student_email_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ibadah",
            new_name="idx_ibadah_siswa_tgl",
            old_name="kesantrian__siswa_i_a89039_idx",
        ),
        migrations.RenameIndex(
            model_name="ibadah",
            new_name="idx_ibadah_tgl_jenis",
            old_name="kesantrian__tanggal_18187c_idx",
        ),
        migrations.RenameIndex(
            model_name="ibadah",
            new_name="idx_ibadah_jenis_waktu",
            old_name="kesantrian__jenis_5b6659_idx",
        ),
        migrations.RenameIndex(
            model_name="pembinaan",
            new_name="idx_pembinaan_siswa_tgl",
            old_name="kesantrian__siswa_i_15e9c4_idx",
        ),
        migrations.RenameIndex(
            model_name="pembinaan",
            new_name="idx_pembinaan_kategori",
            old_name="kesantrian__kategor_fb4582_idx",
        ),
        migrations.RenameIndex(
            model_name="pembinaan",
            new_name="idx_pembinaan_tingkat",
            old_name="kesantrian__tingkat_18f00c_idx",
        ),
        migrations.AddIndex(
            model_name="halaqohmember",
            index=models.Index(
                fields=["siswa", "aktif"], name="idx_halaqoh_member_siswa"
            ),
        ),
        migrations.AddIndex(
            model_name="halaqohmember",
            index=models.Index(
                fields=["halaqoh", "aktif"], name="idx_halaqoh_member_halaqoh"
            ),
        ),
        migrations.AddIndex(
            model_name="halaqohmember",
            index=models.Index(
                fields=["tanggal_gabung"], name="idx_halaqoh_member_tgl"
            ),
        ),
        migrations.AddIndex(
            model_name="ibadah",
            index=models.Index(
                fields=["siswa", "jenis", "status"],
                name="idx_ibadah_siswa_jenis_status",
            ),
        ),
        migrations.AddIndex(
            model_name="ibadah",
            index=models.Index(fields=["tanggal"], name="idx_ibadah_tanggal"),
        ),
        migrations.AddIndex(
            model_name="ibadah",
            index=models.Index(fields=["status"], name="idx_ibadah_status"),
        ),
        migrations.AddIndex(
            model_name="pembinaan",
            index=models.Index(
                fields=["siswa", "kategori"], name="idx_pembinaan_siswa_kat"
            ),
        ),
        migrations.AddIndex(
            model_name="pembinaan",
            index=models.Index(fields=["tanggal"], name="idx_pembinaan_tanggal"),
        ),
        migrations.AddIndex(
            model_name="targethafalan",
            index=models.Index(
                fields=["siswa", "tahun_ajaran"], name="idx_hafalan_siswa_tahun"
            ),
        ),
        migrations.AddIndex(
            model_name="targethafalan",
            index=models.Index(
                fields=["semester", "tahun_ajaran"], name="idx_hafalan_sem_tahun"
            ),
        ),
    ]
