# Generated by Django 5.2.10 on 2026-03-11 02:15

import apps.kesantrian.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kesantrian", "0002_add_performance_indexes"),
        (
            "students",
            "0002_student_aktif_student_current_hafalan_student_email_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvalRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tanggal", models.DateField()),
                (
                    "jam_pelajaran",
                    models.CharField(
                        help_text="Jam pelajaran yang digantikan, misal: JP 1-2",
                        max_length=20,
                    ),
                ),
                ("kelas", models.CharField(max_length=20)),
                ("mata_pelajaran", models.CharField(max_length=100)),
                (
                    "alasan",
                    models.CharField(
                        choices=[
                            ("sakit", "Sakit"),
                            ("izin", "Izin Pribadi"),
                            ("dinas", "Tugas Dinas"),
                            ("darurat", "Keperluan Darurat"),
                            ("cuti", "Cuti"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "keterangan",
                    models.TextField(
                        blank=True, help_text="Keterangan tambahan", null=True
                    ),
                ),
                (
                    "bukti_file",
                    models.FileField(
                        blank=True,
                        help_text="Bukti surat izin/keterangan",
                        null=True,
                        upload_to="inval_bukti/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verifikasi"),
                            ("verified", "Terverifikasi"),
                            ("rejected", "Ditolak"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_by", models.CharField(blank=True, max_length=50, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "evaluation_created",
                    models.BooleanField(
                        default=False, help_text="Flag apakah evaluasi sudah dibuat"
                    ),
                ),
                ("recorded_by_username", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guru_absent",
                    models.ForeignKey(
                        help_text="Ustadz yang tidak hadir",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inval_absences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guru_pengganti",
                    models.ForeignKey(
                        help_text="Ustadz pengganti",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inval_substitutes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="Ustadz Piket yang mencatat",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inval_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inval Record",
                "verbose_name_plural": "Inval Records",
                "db_table": "inval_records",
                "ordering": ["-tanggal", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeEvaluation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tanggal", models.DateField()),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("prestasi", "Prestasi"),
                            ("pelanggaran", "Pelanggaran"),
                            ("inval_plus", "Bonus Inval (Pengganti)"),
                            ("inval_minus", "Potongan Inval (Absen)"),
                            ("kehadiran", "Bonus Kehadiran"),
                            ("tugas_tambahan", "Tugas Tambahan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "poin",
                    models.IntegerField(
                        help_text="Poin evaluasi (positif untuk prestasi, negatif untuk pelanggaran)"
                    ),
                ),
                ("keterangan", models.TextField(help_text="Deskripsi evaluasi")),
                ("tahun_ajaran", models.CharField(max_length=10)),
                (
                    "semester",
                    models.CharField(
                        choices=[("Ganjil", "Ganjil"), ("Genap", "Genap")],
                        max_length=10,
                    ),
                ),
                ("created_by", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Ustadz/Ustadzah yang dievaluasi",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inval_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations",
                        to="kesantrian.invalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Evaluation",
                "verbose_name_plural": "Employee Evaluations",
                "db_table": "employee_evaluations",
                "ordering": ["-tanggal", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BLPEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "week_start",
                    models.DateField(help_text="Tanggal mulai minggu (Minggu)"),
                ),
                (
                    "week_end",
                    models.DateField(help_text="Tanggal akhir minggu (Sabtu)"),
                ),
                ("tahun_ajaran", models.CharField(max_length=10)),
                (
                    "semester",
                    models.CharField(
                        choices=[("Ganjil", "Ganjil"), ("Genap", "Genap")],
                        max_length=10,
                    ),
                ),
                (
                    "indicator_values",
                    models.JSONField(
                        default=apps.kesantrian.models.get_blp_default_values,
                        help_text="Nilai untuk setiap indikator BLP (59 total)",
                    ),
                ),
                (
                    "bonus_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Bonus poin untuk pencapaian luar biasa (max 95)",
                        validators=[django.core.validators.MaxValueValidator(95)],
                    ),
                ),
                (
                    "bonus_notes",
                    models.TextField(
                        blank=True, help_text="Catatan untuk bonus poin", null=True
                    ),
                ),
                (
                    "total_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Total skor (max 390)"
                    ),
                ),
                (
                    "domain_scores",
                    models.JSONField(default=dict, help_text="Skor per domain"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("locked", "Locked"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Jika True, entry tidak dapat diedit"
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=50, null=True)),
                ("catatan", models.TextField(blank=True, null=True)),
                ("tindak_lanjut", models.TextField(blank=True, null=True)),
                ("pencatat", models.CharField(max_length=100)),
                (
                    "pencatat_username",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blp_entries",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "BLP Entry",
                "verbose_name_plural": "BLP Entries",
                "db_table": "kesantrian_blp_entry",
                "ordering": ["-week_start", "siswa"],
                "indexes": [
                    models.Index(
                        fields=["siswa", "week_start"], name="idx_blp_siswa_week"
                    ),
                    models.Index(
                        fields=["week_start", "week_end"], name="idx_blp_week_range"
                    ),
                    models.Index(
                        fields=["tahun_ajaran", "semester"], name="idx_blp_periode"
                    ),
                    models.Index(fields=["status"], name="idx_blp_status"),
                    models.Index(fields=["is_locked"], name="idx_blp_locked"),
                    models.Index(fields=["total_score"], name="idx_blp_score"),
                ],
                "unique_together": {("siswa", "week_start")},
            },
        ),
        migrations.AddIndex(
            model_name="invalrecord",
            index=models.Index(
                fields=["guru_absent", "tanggal"], name="idx_inval_absent_tgl"
            ),
        ),
        migrations.AddIndex(
            model_name="invalrecord",
            index=models.Index(
                fields=["guru_pengganti", "tanggal"], name="idx_inval_pengganti_tgl"
            ),
        ),
        migrations.AddIndex(
            model_name="invalrecord",
            index=models.Index(fields=["tanggal"], name="idx_inval_tanggal"),
        ),
        migrations.AddIndex(
            model_name="invalrecord",
            index=models.Index(fields=["status"], name="idx_inval_status"),
        ),
        migrations.AddIndex(
            model_name="invalrecord",
            index=models.Index(fields=["kelas"], name="idx_inval_kelas"),
        ),
        migrations.AddIndex(
            model_name="employeeevaluation",
            index=models.Index(
                fields=["user", "tanggal"], name="idx_emp_eval_user_tgl"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeevaluation",
            index=models.Index(fields=["jenis"], name="idx_emp_eval_jenis"),
        ),
        migrations.AddIndex(
            model_name="employeeevaluation",
            index=models.Index(
                fields=["tahun_ajaran", "semester"], name="idx_emp_eval_periode"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeevaluation",
            index=models.Index(fields=["poin"], name="idx_emp_eval_poin"),
        ),
    ]
