# Generated by Django 5.2.10 on 2026-03-13 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kesantrian", "0004_incident_system"),
        ("students", "0003_alumni_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incident",
            options={
                "ordering": ["-created_at", "-tanggal_kejadian"],
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
            },
        ),
        migrations.RemoveIndex(
            model_name="incident",
            name="kesantrian_inc_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="incident",
            name="kesantrian_inc_kat_idx",
        ),
        migrations.RenameIndex(
            model_name="incident",
            new_name="idx_incident_siswa_status",
            old_name="kesantrian_inc_siswa_idx",
        ),
        migrations.RenameIndex(
            model_name="incidentcomment",
            new_name="idx_comment_incident_time",
            old_name="kesantrian_cmt_inc_idx",
        ),
        migrations.RenameIndex(
            model_name="incidentcomment",
            new_name="idx_comment_visibility",
            old_name="kesantrian_cmt_vis_idx",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="pelapor_role_display",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="resolved_at",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="resolved_by",
        ),
        migrations.AddField(
            model_name="incident",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Ustadz yang ditugaskan menangani",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="deadline_tindak_lanjut",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="diputuskan_oleh",
            field=models.ForeignKey(
                blank=True,
                help_text="Pimpinan yang memberikan keputusan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents_decided",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="lokasi",
            field=models.CharField(
                blank=True, help_text="Lokasi kejadian", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="semester",
            field=models.CharField(
                choices=[("Ganjil", "Ganjil"), ("Genap", "Genap")],
                default="Ganjil",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="tahun_ajaran",
            field=models.CharField(default="2025/2026", max_length=10),
        ),
        migrations.AddField(
            model_name="incident",
            name="tanggal_keputusan",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="tindak_lanjut",
            field=models.TextField(
                blank=True, help_text="Rencana tindak lanjut", null=True
            ),
        ),
        migrations.AddField(
            model_name="incidentcomment",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="incident_attachments/"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="deskripsi",
            field=models.TextField(help_text="Deskripsi lengkap kejadian"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="incident",
            name="judul",
            field=models.CharField(
                help_text="Judul/ringkasan kejadian", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="kategori",
            field=models.CharField(
                choices=[
                    ("perilaku", "Perilaku/Akhlak"),
                    ("kedisiplinan", "Kedisiplinan"),
                    ("akademik", "Akademik"),
                    ("kesehatan", "Kesehatan"),
                    ("sosial", "Interaksi Sosial"),
                    ("keluarga", "Masalah Keluarga"),
                    ("lainnya", "Lainnya"),
                ],
                default="perilaku",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="keputusan_final",
            field=models.TextField(
                blank=True, help_text="Keputusan akhir dari Mudir", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="pelapor",
            field=models.ForeignKey(
                help_text="Ustadz yang melaporkan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents_reported",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="pelapor_role",
            field=models.CharField(
                help_text="Role pelapor saat melapor (BK, Wali Kelas, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="siswa",
            field=models.ForeignKey(
                help_text="Santri yang terkait",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="tanggal_kejadian",
            field=models.DateField(help_text="Tanggal kejadian terjadi"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="tingkat",
            field=models.CharField(
                choices=[
                    ("ringan", "Ringan"),
                    ("sedang", "Sedang"),
                    ("berat", "Berat"),
                    ("kritis", "Kritis"),
                ],
                default="ringan",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="incidentcomment",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incident_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incidentcomment",
            name="author_role",
            field=models.CharField(
                help_text="Role penulis saat berkomentar", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="incidentcomment",
            name="author_role_display",
            field=models.CharField(
                blank=True,
                help_text="Nama jabatan untuk display (e.g., 'Guru BK', 'Mudir')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="incidentcomment",
            name="comment_type",
            field=models.CharField(
                choices=[
                    ("observation", "Observasi"),
                    ("suggestion", "Saran"),
                    ("evaluation", "Evaluasi"),
                    ("decision", "Keputusan"),
                    ("follow_up", "Tindak Lanjut"),
                    ("note", "Catatan"),
                ],
                default="note",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="incidentcomment",
            name="content",
            field=models.TextField(help_text="Isi komentar/tanggapan"),
        ),
        migrations.AlterField(
            model_name="incidentcomment",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="incidentcomment",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("internal", "Internal (Hanya Ustadz)"),
                    ("public", "Public (Termasuk Wali Santri)"),
                    ("final_decision", "Final Decision"),
                ],
                default="internal",
                help_text="Siapa yang bisa melihat komentar ini",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["status"], name="idx_incident_status"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["kategori"], name="idx_incident_kategori"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["tingkat"], name="idx_incident_tingkat"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["tanggal_kejadian"], name="idx_incident_tanggal"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["pelapor"], name="idx_incident_pelapor"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["tahun_ajaran", "semester"], name="idx_incident_periode"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentcomment",
            index=models.Index(fields=["author"], name="idx_comment_author"),
        ),
        migrations.AddIndex(
            model_name="incidentcomment",
            index=models.Index(fields=["comment_type"], name="idx_comment_type"),
        ),
        migrations.AlterModelTable(
            name="incident",
            table="kesantrian_incident",
        ),
        migrations.AlterModelTable(
            name="incidentcomment",
            table="kesantrian_incident_comment",
        ),
    ]
