# Generated by Django 5.2.10 on 2026-03-21 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("kesantrian", "0006_add_asatidz_evaluation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndikatorKinerja",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nama_indikator",
                    models.CharField(
                        help_text="Nama indikator penilaian, misal: 'Kerjasama Tim'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "deskripsi",
                    models.TextField(
                        blank=True,
                        help_text="Deskripsi lengkap tentang indikator ini",
                        null=True,
                    ),
                ),
                (
                    "urutan",
                    models.PositiveIntegerField(
                        default=0, help_text="Urutan tampilan (0 = paling atas)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Jika False, indikator tidak akan muncul di form penilaian",
                    ),
                ),
                (
                    "is_auto_calculated",
                    models.BooleanField(
                        default=False,
                        help_text="Jika True, nilai diambil dari data lain (misal: absensi untuk Kedisiplinan)",
                    ),
                ),
                (
                    "auto_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("attendance", "Absensi Kelas"),
                            ("inval", "Data Penggantian Mengajar"),
                            ("evaluation", "Evaluasi Santri"),
                        ],
                        help_text="Sumber data untuk indikator auto-calculated",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bobot",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Bobot indikator untuk perhitungan rata-rata tertimbang",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Indikator Kinerja",
                "verbose_name_plural": "Indikator Kinerja",
                "db_table": "kesantrian_indikator_kinerja",
                "ordering": ["urutan", "nama_indikator"],
            },
        ),
        migrations.CreateModel(
            name="PenilaianKinerjaAsatidz",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tahun_ajaran_nama",
                    models.CharField(
                        default="2025/2026",
                        help_text="Nama tahun ajaran (backup jika FK null)",
                        max_length=20,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("Ganjil", "Ganjil"), ("Genap", "Genap")],
                        default="Ganjil",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("finalized", "Finalized"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "catatan_tambahan",
                    models.TextField(
                        blank=True, help_text="Catatan umum dari penilai", null=True
                    ),
                ),
                (
                    "rata_rata_nilai",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rata-rata tertimbang (1.00 - 5.00)",
                        max_digits=3,
                    ),
                ),
                (
                    "total_indikator",
                    models.PositiveIntegerField(
                        default=0, help_text="Jumlah indikator yang dinilai"
                    ),
                ),
                (
                    "tanggal_penilaian",
                    models.DateField(
                        auto_now_add=True, help_text="Tanggal penilaian dibuat"
                    ),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True, help_text="Waktu finalisasi penilaian", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "penilai",
                    models.ForeignKey(
                        help_text="Mudir/Pimpinan yang memberikan penilaian",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="penilaian_diberikan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tahun_ajaran",
                    models.ForeignKey(
                        blank=True,
                        help_text="Periode tahun ajaran",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="penilaian_kinerja",
                        to="core.tahunajaran",
                    ),
                ),
                (
                    "ustadz",
                    models.ForeignKey(
                        help_text="Ustadz/Karyawan yang dinilai",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penilaian_kinerja",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Penilaian Kinerja Asatidz",
                "verbose_name_plural": "Penilaian Kinerja Asatidz",
                "db_table": "kesantrian_penilaian_kinerja",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetailPenilaianKinerja",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nilai_bintang",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "⭐ Sangat Kurang"),
                            (2, "⭐⭐ Kurang"),
                            (3, "⭐⭐⭐ Cukup"),
                            (4, "⭐⭐⭐⭐ Baik"),
                            (5, "⭐⭐⭐⭐⭐ Sangat Baik"),
                        ],
                        help_text="Rating bintang 1-5",
                        null=True,
                    ),
                ),
                (
                    "catatan",
                    models.TextField(
                        blank=True,
                        help_text="Catatan khusus untuk indikator ini",
                        null=True,
                    ),
                ),
                (
                    "is_auto_filled",
                    models.BooleanField(
                        default=False,
                        help_text="True jika nilai diisi otomatis dari data lain",
                    ),
                ),
                (
                    "auto_calculation_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data detail perhitungan otomatis",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "indikator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detail_penilaian",
                        to="kesantrian.indikatorkinerja",
                    ),
                ),
                (
                    "penilaian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_penilaian",
                        to="kesantrian.penilaiankinerjaasatidz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detail Penilaian Kinerja",
                "verbose_name_plural": "Detail Penilaian Kinerja",
                "db_table": "kesantrian_detail_penilaian_kinerja",
                "ordering": ["indikator__urutan", "indikator__nama_indikator"],
            },
        ),
        migrations.AddIndex(
            model_name="penilaiankinerjaasatidz",
            index=models.Index(
                fields=["ustadz", "tahun_ajaran_nama"],
                name="idx_penilaian_ustadz_tahun",
            ),
        ),
        migrations.AddIndex(
            model_name="penilaiankinerjaasatidz",
            index=models.Index(fields=["status"], name="idx_penilaian_status"),
        ),
        migrations.AddIndex(
            model_name="penilaiankinerjaasatidz",
            index=models.Index(fields=["penilai"], name="idx_penilaian_penilai"),
        ),
        migrations.AddIndex(
            model_name="penilaiankinerjaasatidz",
            index=models.Index(
                fields=["tanggal_penilaian"], name="idx_penilaian_tanggal"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="penilaiankinerjaasatidz",
            unique_together={("ustadz", "tahun_ajaran_nama", "semester")},
        ),
        migrations.AddIndex(
            model_name="detailpenilaiankinerja",
            index=models.Index(
                fields=["penilaian", "indikator"], name="idx_detail_penilaian_indikator"
            ),
        ),
        migrations.AddIndex(
            model_name="detailpenilaiankinerja",
            index=models.Index(fields=["nilai_bintang"], name="idx_detail_nilai"),
        ),
        migrations.AlterUniqueTogether(
            name="detailpenilaiankinerja",
            unique_together={("penilaian", "indikator")},
        ),
    ]
