# Generated by Django 5.2.10 on 2026-04-21 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('kesantrian', '0007_penilaian_kinerja_star_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IzinGuru',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jenis_izin', models.CharField(choices=[('sakit', 'Sakit'), ('dinas', 'Dinas Luar'), ('keperluan_keluarga', 'Keperluan Keluarga'), ('lainnya', 'Lainnya')], help_text='Jenis izin yang diajukan', max_length=30)),
                ('tanggal_mulai', models.DateField(help_text='Tanggal mulai izin')),
                ('tanggal_selesai', models.DateField(help_text='Tanggal selesai izin')),
                ('keterangan', models.TextField(help_text='Keterangan/alasan izin')),
                ('foto_surat', models.ImageField(help_text='Foto surat izin/keterangan (WAJIB)', upload_to='izin_guru/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(help_text='Guru/Ustadz yang mengajukan izin', on_delete=django.db.models.deletion.CASCADE, related_name='izin_guru', to=settings.AUTH_USER_MODEL)),
                ('tahun_ajaran', models.ForeignKey(help_text='Tahun ajaran saat pengajuan', on_delete=django.db.models.deletion.CASCADE, related_name='izin_guru', to='core.tahunajaran')),
            ],
            options={
                'verbose_name': 'Izin Guru',
                'verbose_name_plural': 'Izin Guru',
                'db_table': 'kesantrian_izin_guru',
                'ordering': ['-tanggal_mulai', '-created_at'],
                'indexes': [models.Index(fields=['guru', 'tanggal_mulai'], name='idx_izin_guru_tgl'), models.Index(fields=['jenis_izin'], name='idx_izin_jenis'), models.Index(fields=['tahun_ajaran'], name='idx_izin_tahun_ajaran'), models.Index(fields=['tanggal_mulai', 'tanggal_selesai'], name='idx_izin_periode')],
            },
        ),
    ]
