# Generated by Django 5.2.10 on 2026-05-04 01:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_master_mapel_unique'),
        ('kesantrian', '0008_add_izin_guru_model'),
        ('students', '0008_add_schedule_jam_range_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HafalanRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField(help_text='Tanggal setoran hafalan')),
                ('jumlah_halaman', models.PositiveIntegerField(help_text='Jumlah halaman yang ditambah hari ini')),
                ('juz', models.PositiveIntegerField(blank=True, help_text='Juz yang dihafal (1-30, boleh loncat)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('halaman_dari', models.PositiveIntegerField(blank=True, help_text='Halaman awal (1-604)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(604)])),
                ('halaman_sampai', models.PositiveIntegerField(blank=True, help_text='Halaman akhir (1-604)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(604)])),
                ('catatan', models.TextField(blank=True, help_text='Catatan tambahan dari pembimbing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_by', models.ForeignKey(help_text='Musyrif/Guru yang menginput', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hafalan_inputs', to=settings.AUTH_USER_MODEL)),
                ('siswa', models.ForeignKey(help_text='Santri yang dihafal', on_delete=django.db.models.deletion.CASCADE, related_name='hafalan_records', to='students.student', to_field='nisn')),
                ('tahun_ajaran', models.ForeignKey(help_text='Tahun ajaran aktif saat input', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tahunajaran')),
            ],
            options={
                'verbose_name': 'Hafalan Record',
                'verbose_name_plural': 'Hafalan Records',
                'db_table': 'kesantrian_hafalan_record',
                'ordering': ['-tanggal', '-created_at'],
                'indexes': [models.Index(fields=['siswa', 'tanggal'], name='idx_hafalan_rec_siswa_tgl'), models.Index(fields=['tanggal'], name='idx_hafalan_rec_tanggal'), models.Index(fields=['juz'], name='idx_hafalan_rec_juz'), models.Index(fields=['input_by'], name='idx_hafalan_rec_input_by'), models.Index(fields=['tahun_ajaran'], name='idx_hafalan_rec_tahun')],
            },
        ),
    ]
