# Generated by Django 5.2.10 on 2026-05-06 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesantrian', '0009_hafalanrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='izinguru',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Waktu persetujuan/penolakan', null=True),
        ),
        migrations.AddField(
            model_name='izinguru',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Pimpinan yang menyetujui/menolak', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_izin_guru', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='izinguru',
            name='catatan_approval',
            field=models.TextField(blank=True, default='', help_text='Catatan dari approver saat menyetujui/menolak'),
        ),
        migrations.AddField(
            model_name='izinguru',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', help_text='Status persetujuan izin', max_length=20),
        ),
    ]
