# Generated by Django 5.2.10 on 2026-05-07 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesantrian', '0010_izinguru_approved_at_izinguru_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KritikSaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonim', models.BooleanField(default=False, help_text='Jika True, identitas pengirim disembunyikan dari pimpinan')),
                ('jenis', models.CharField(choices=[('kritik', 'Kritik'), ('saran', 'Saran')], max_length=10)),
                ('unit', models.CharField(choices=[('putra', 'Putra'), ('putri', 'Putri'), ('umum', 'Umum')], default='umum', max_length=10)),
                ('isi', models.TextField(help_text='Isi kritik atau saran')),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('dibaca', 'Dibaca')], default='baru', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pengirim', models.ForeignKey(blank=True, help_text='Kosong jika anonim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kritik_saran', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kritik & Saran',
                'verbose_name_plural': 'Kritik & Saran',
                'ordering': ['-created_at'],
            },
        ),
    ]
