# Generated by Django 5.2.10 on 2026-05-07 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_master_mapel_unique'),
        ('kesantrian', '0011_kritiksaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PertemuanPengasuhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, default='')),
                ('tanggal', models.DateField()),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
                ('lokasi', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pertemuan_dibuat', to=settings.AUTH_USER_MODEL)),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertemuan_pengasuhan', to='core.tahunajaran')),
            ],
            options={
                'verbose_name': 'Pertemuan Pengasuhan',
                'verbose_name_plural': 'Pertemuan Pengasuhan',
                'ordering': ['-tanggal', '-waktu_mulai'],
            },
        ),
        migrations.CreateModel(
            name='PresensiPertemuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('tidak_hadir', 'Tidak Hadir'), ('izin', 'Izin')], default='tidak_hadir', max_length=20)),
                ('catatan', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pertemuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='kesantrian.pertemuanpengasuhan')),
                ('walisantri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_pertemuan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presensi Pertemuan',
                'verbose_name_plural': 'Presensi Pertemuan',
                'unique_together': {('pertemuan', 'walisantri')},
            },
        ),
    ]
