# Generated by Django 5.2.10 on 2026-05-08 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_master_mapel_unique'),
        ('kesantrian', '0012_pertemuanpengasuhan_presensipertemuan'),
        ('students', '0008_add_schedule_jam_range_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pertemuanpengasuhan',
            options={'ordering': ['-tanggal'], 'verbose_name': 'Pertemuan Pengasuhan', 'verbose_name_plural': 'Pertemuan Pengasuhan'},
        ),
        migrations.RemoveField(
            model_name='pertemuanpengasuhan',
            name='tahun_ajaran',
        ),
        migrations.RemoveField(
            model_name='pertemuanpengasuhan',
            name='waktu_mulai',
        ),
        migrations.RemoveField(
            model_name='pertemuanpengasuhan',
            name='waktu_selesai',
        ),
        migrations.AddField(
            model_name='pertemuanpengasuhan',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto dokumentasi pertemuan', null=True, upload_to='pertemuan_pengasuhan/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='presensipertemuan',
            name='santri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presensi_pertemuan', to='students.student'),
        ),
        migrations.AlterField(
            model_name='presensipertemuan',
            name='status',
            field=models.CharField(choices=[('hadir', 'Hadir'), ('tidak_hadir', 'Tidak Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit')], default='tidak_hadir', max_length=20),
        ),
        migrations.CreateModel(
            name='KelompokPengasuhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kelas', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pengasuh', models.ForeignKey(help_text='Ustadz pengasuh utama', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelompok_sebagai_pengasuh', to=settings.AUTH_USER_MODEL)),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelompok_pengasuhan', to='core.tahunajaran')),
                ('wakil_pengasuh', models.ForeignKey(blank=True, help_text='Wakil pengasuh (opsional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelompok_sebagai_wakil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kelompok Pengasuhan',
                'verbose_name_plural': 'Kelompok Pengasuhan',
                'ordering': ['kelas', 'nama'],
            },
        ),
        migrations.AddField(
            model_name='pertemuanpengasuhan',
            name='kelompok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pertemuan', to='kesantrian.kelompokpengasuhan'),
        ),
        migrations.RenameField(
            model_name='presensipertemuan',
            old_name='walisantri',
            new_name='santri',
        ),
        migrations.AlterField(
            model_name='presensipertemuan',
            name='santri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presensi_pertemuan', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='presensipertemuan',
            unique_together={('pertemuan', 'santri')},
        ),
    ]
