# Generated by Django 5.2.10 on 2026-05-13 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_master_mapel_unique'),
        ('kesantrian', '0013_alter_pertemuanpengasuhan_options_and_more'),
        ('students', '0008_add_schedule_jam_range_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahfidzSantri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Juz Hafal', 'Juz Hafal'), ('Juz Uji', 'Juz Uji'), ("Tasmi'", "Tasmi'"), ('Munaqosyah', 'Munaqosyah')], max_length=20)),
                ('nilai', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('jumlah_juz', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('total_juz_target', models.DecimalField(decimal_places=1, default=30, max_digits=4)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tahfidz_records', to='students.student')),
                ('tahun_ajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tahunajaran')),
            ],
            options={
                'db_table': 'kesantrian_tahfidz_santri',
                'unique_together': {('siswa', 'kategori', 'tahun_ajaran')},
            },
        ),
        migrations.CreateModel(
            name='TartilSantri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jilid', models.CharField(choices=[('Jilid 1', 'Jilid 1'), ('Jilid 2', 'Jilid 2'), ('Jilid 3', 'Jilid 3'), ('Jilid 4', 'Jilid 4'), ('Jilid 5', 'Jilid 5'), ('Jilid 6', 'Jilid 6')], max_length=20)),
                ('nilai', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('capaian_persen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status_lulus', models.BooleanField(default=False)),
                ('tanggal_lulus', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tartil_records', to='students.student')),
                ('tahun_ajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tahunajaran')),
            ],
            options={
                'db_table': 'kesantrian_tartil_santri',
                'unique_together': {('siswa', 'jilid', 'tahun_ajaran')},
            },
        ),
    ]
