# Generated by Django 5.2.10 on 2026-05-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesantrian', '0014_tahfidzsantri_tartilsantri'),
        ('students', '0008_add_schedule_jam_range_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='KelompokAnggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='kesantrian.kelompokpengasuhan')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelompok_anggota', to='students.student')),
            ],
            options={
                'verbose_name': 'Anggota Kelompok',
                'verbose_name_plural': 'Anggota Kelompok',
                'ordering': ['santri__nama'],
                'unique_together': {('kelompok', 'santri')},
            },
        ),
    ]
