# Generated by Django 5.2.10 on 2026-05-14 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesantrian', '0015_kelompokanggota'),
        ('students', '0008_add_schedule_jam_range_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KompetensiSantri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_khidmat', models.CharField(choices=[('aktif', 'Aktif'), ('tidak_aktif', 'Tidak Aktif'), ('mutakhirij', 'Mutakhirij')], default='aktif', max_length=20)),
                ('keterangan_khidmat', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru_tahfidz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='santri_tahfidz', to=settings.AUTH_USER_MODEL)),
                ('guru_tartil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='santri_tartil', to=settings.AUTH_USER_MODEL)),
                ('santri', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kompetensi', to='students.student', to_field='nisn')),
            ],
        ),
    ]
