# Generated by Django 5.2.10 on 2026-05-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesantrian', '0016_kompetensisantri'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelompokanggota',
            name='is_ketua',
            field=models.BooleanField(default=False),
        ),
    ]
