# Generated by Django 5.2.10 on 2026-05-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesantrian', '0017_kelompokanggota_is_ketua'),
    ]

    operations = [
        migrations.AddField(
            model_name='hafalanrecord',
            name='status',
            field=models.CharField(choices=[('lancar', 'Lancar'), ('perlu_ulang', 'Perlu Ulang'), ('belum_selesai', 'Belum Selesai')], default='lancar', max_length=20),
        ),
    ]
