# Generated by Django 5.2.10 on 2026-05-16 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_master_mapel_unique'),
        ('kesantrian', '0018_hafalanrecord_status'),
        ('students', '0008_add_schedule_jam_range_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KelompokHafalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tahun_ajaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tahunajaran')),
                ('ustadz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelompok_hafalan_diampu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kelas', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='KelompokHafalanAnggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_urut', models.PositiveIntegerField(default=0)),
                ('is_ketua', models.BooleanField(default=False)),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='kesantrian.kelompokhafalan')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelompok_hafalan_anggota', to='students.student', to_field='nisn')),
            ],
            options={
                'ordering': ['nomor_urut'],
                'unique_together': {('kelompok', 'siswa')},
            },
        ),
    ]
