# Generated by Django 4.2.30 on 2026-05-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesantrian', '0019_kelompokhafalan_kelompokhafalananggota'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto bukti kejadian', null=True, upload_to='incidents/foto/'),
        ),
    ]
