# Generated by Django 4.2.30 on 2026-05-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesantrian', '0020_incident_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blpentry',
            name='bonus_notes',
        ),
        migrations.RemoveField(
            model_name='blpentry',
            name='bonus_points',
        ),
        migrations.AlterField(
            model_name='blpentry',
            name='total_score',
            field=models.FloatField(default=0.0, help_text='Persentase total skor (0.0 - 100.0)'),
        ),
    ]
