# Generated by Django 5.2.10 on 2026-02-26 02:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "students",
            "0002_student_aktif_student_current_hafalan_student_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LaporanKeuangan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bulan", models.PositiveSmallIntegerField()),
                ("tahun", models.PositiveIntegerField()),
                (
                    "total_tagihan",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_terbayar",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_tunggakan",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("jumlah_siswa_lunas", models.PositiveIntegerField(default=0)),
                ("jumlah_siswa_tunggakan", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Laporan Keuangan",
                "verbose_name_plural": "Laporan Keuangan",
                "db_table": "finance_laporan",
                "ordering": ["-tahun", "-bulan"],
                "unique_together": {("bulan", "tahun")},
            },
        ),
        migrations.CreateModel(
            name="Tarif",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nama",
                    models.CharField(
                        help_text="Nama tarif, misal: SPP Kelas X, Uang Gedung 2024",
                        max_length=100,
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("spp", "SPP (Bulanan)"),
                            ("gedung", "Uang Gedung (Tahunan)"),
                            ("seragam", "Seragam"),
                            ("buku", "Buku & Perlengkapan"),
                            ("kegiatan", "Kegiatan Sekolah"),
                            ("wisuda", "Wisuda/Kelulusan"),
                            ("lainnya", "Lainnya"),
                        ],
                        default="spp",
                        max_length=20,
                    ),
                ),
                (
                    "frekuensi",
                    models.CharField(
                        choices=[
                            ("bulanan", "Bulanan"),
                            ("semester", "Per Semester"),
                            ("tahunan", "Tahunan"),
                            ("sekali", "Sekali Bayar"),
                        ],
                        default="bulanan",
                        help_text="Frekuensi pembayaran",
                        max_length=20,
                    ),
                ),
                (
                    "nominal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Nominal tarif dalam Rupiah",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tahun_ajaran",
                    models.CharField(help_text="Format: 2024/2025", max_length=10),
                ),
                (
                    "kelas",
                    models.CharField(
                        blank=True,
                        help_text="Kosongkan jika berlaku untuk semua kelas",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        blank=True,
                        help_text="Kosongkan jika berlaku untuk semua program",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "deskripsi",
                    models.TextField(
                        blank=True,
                        help_text="Keterangan tambahan tentang tarif",
                        null=True,
                    ),
                ),
                (
                    "aktif",
                    models.BooleanField(
                        default=True,
                        help_text="Tarif aktif akan digunakan untuk generate tagihan",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tarif",
                "verbose_name_plural": "Tarif",
                "db_table": "finance_tarif",
                "ordering": ["kategori", "nama"],
                "indexes": [
                    models.Index(
                        fields=["kategori"], name="finance_tar_kategor_f1d96f_idx"
                    ),
                    models.Index(
                        fields=["tahun_ajaran"], name="finance_tar_tahun_a_2713b6_idx"
                    ),
                    models.Index(fields=["aktif"], name="finance_tar_aktif_a875db_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tagihan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "bulan",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Januari"),
                            (2, "Februari"),
                            (3, "Maret"),
                            (4, "April"),
                            (5, "Mei"),
                            (6, "Juni"),
                            (7, "Juli"),
                            (8, "Agustus"),
                            (9, "September"),
                            (10, "Oktober"),
                            (11, "November"),
                            (12, "Desember"),
                        ],
                        help_text="Bulan tagihan (untuk pembayaran bulanan)",
                        null=True,
                    ),
                ),
                ("tahun", models.PositiveIntegerField(help_text="Tahun tagihan")),
                (
                    "nominal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Nominal tagihan (bisa berbeda dari tarif jika ada diskon/denda)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "diskon",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Potongan/diskon",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "denda",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Denda keterlambatan",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total = Nominal - Diskon + Denda",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "terbayar",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Jumlah yang sudah dibayar",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "sisa",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sisa tagihan = Total - Terbayar",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("belum_bayar", "Belum Bayar"),
                            ("sebagian", "Dibayar Sebagian"),
                            ("lunas", "Lunas"),
                            ("lewat_jatuh_tempo", "Lewat Jatuh Tempo"),
                        ],
                        default="belum_bayar",
                        max_length=20,
                    ),
                ),
                (
                    "jatuh_tempo",
                    models.DateField(help_text="Tanggal jatuh tempo pembayaran"),
                ),
                (
                    "keterangan",
                    models.TextField(
                        blank=True, help_text="Catatan tambahan", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Username pembuat tagihan",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "siswa",
                    models.ForeignKey(
                        help_text="Siswa yang memiliki tagihan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tagihan",
                        to="students.student",
                    ),
                ),
                (
                    "tarif",
                    models.ForeignKey(
                        help_text="Tarif yang ditagihkan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tagihan",
                        to="finance.tarif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagihan",
                "verbose_name_plural": "Tagihan",
                "db_table": "finance_tagihan",
                "ordering": ["-tahun", "-bulan", "siswa"],
            },
        ),
        migrations.CreateModel(
            name="Pembayaran",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tanggal",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Tanggal pembayaran",
                    ),
                ),
                (
                    "nominal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Nominal pembayaran",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "metode",
                    models.CharField(
                        choices=[
                            ("tunai", "Tunai"),
                            ("transfer", "Transfer Bank"),
                            ("qris", "QRIS"),
                            ("virtual_account", "Virtual Account"),
                            ("lainnya", "Lainnya"),
                        ],
                        default="tunai",
                        max_length=20,
                    ),
                ),
                (
                    "bukti",
                    models.ImageField(
                        blank=True,
                        help_text="Bukti pembayaran (foto struk/transfer)",
                        null=True,
                        upload_to="pembayaran/%Y/%m/",
                    ),
                ),
                (
                    "nomor_referensi",
                    models.CharField(
                        blank=True,
                        help_text="Nomor referensi transfer/transaksi",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "terverifikasi",
                    models.BooleanField(
                        default=False, help_text="Apakah pembayaran sudah diverifikasi"
                    ),
                ),
                (
                    "tanggal_verifikasi",
                    models.DateTimeField(
                        blank=True, help_text="Tanggal verifikasi pembayaran", null=True
                    ),
                ),
                (
                    "verified_by",
                    models.CharField(
                        blank=True,
                        help_text="Username yang memverifikasi",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "keterangan",
                    models.TextField(
                        blank=True, help_text="Catatan tambahan", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Username yang membuat record",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tagihan",
                    models.ForeignKey(
                        help_text="Tagihan yang dibayar",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pembayaran",
                        to="finance.tagihan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pembayaran",
                "verbose_name_plural": "Pembayaran",
                "db_table": "finance_pembayaran",
                "ordering": ["-tanggal"],
                "indexes": [
                    models.Index(
                        fields=["tagihan"], name="finance_pem_tagihan_d699e3_idx"
                    ),
                    models.Index(
                        fields=["tanggal"], name="finance_pem_tanggal_61d3b7_idx"
                    ),
                    models.Index(
                        fields=["terverifikasi"], name="finance_pem_terveri_bc4915_idx"
                    ),
                    models.Index(
                        fields=["metode"], name="finance_pem_metode_454112_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="tagihan",
            index=models.Index(fields=["siswa"], name="finance_tag_siswa_i_a10d12_idx"),
        ),
        migrations.AddIndex(
            model_name="tagihan",
            index=models.Index(fields=["tarif"], name="finance_tag_tarif_i_8c981f_idx"),
        ),
        migrations.AddIndex(
            model_name="tagihan",
            index=models.Index(fields=["status"], name="finance_tag_status_1d1ebc_idx"),
        ),
        migrations.AddIndex(
            model_name="tagihan",
            index=models.Index(
                fields=["tahun", "bulan"], name="finance_tag_tahun_fb9262_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tagihan",
            index=models.Index(
                fields=["jatuh_tempo"], name="finance_tag_jatuh_t_c0e60d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tagihan",
            unique_together={("siswa", "tarif", "bulan", "tahun")},
        ),
    ]
