# Generated by Django 5.2.10 on 2026-02-27 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_audit_trail_and_invoice"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tagihan",
            name="finance_tag_no_invo_idx",
        ),
    ]
