# Generated by Django 5.2.10 on 2026-01-24 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "students",
            "0002_student_aktif_student_current_hafalan_student_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mata_pelajaran", models.CharField(max_length=100)),
                ("nilai", models.IntegerField()),
                (
                    "semester",
                    models.CharField(
                        choices=[("Ganjil", "Ganjil"), ("Genap", "Genap")],
                        max_length=20,
                    ),
                ),
                ("tahun_ajaran", models.CharField(max_length=10)),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("UH", "Ulangan Harian"),
                            ("UTS", "Ujian Tengah Semester"),
                            ("UAS", "Ujian Akhir Semester"),
                            ("Tugas", "Tugas"),
                            ("Proyek", "Proyek"),
                        ],
                        max_length=50,
                    ),
                ),
                ("kelas", models.CharField(max_length=20)),
                ("guru", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nisn",
                    models.ForeignKey(
                        db_column="nisn",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nilai",
                "verbose_name_plural": "Nilai",
                "db_table": "grades",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["nisn"], name="grades_nisn_8aebea_idx"),
                    models.Index(fields=["kelas"], name="grades_kelas_c9910d_idx"),
                    models.Index(fields=["semester"], name="grades_semeste_1c36a6_idx"),
                    models.Index(
                        fields=["tahun_ajaran"], name="grades_tahun_a_3bc72a_idx"
                    ),
                ],
            },
        ),
    ]
