# Generated by Django 4.2.29 on 2026-04-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="materi",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Materi/topik yang dinilai",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="jenis",
            field=models.CharField(
                choices=[
                    ("penugasan", "Penugasan"),
                    ("tes_tulis", "Tes Tulis"),
                    ("tes_lisan", "Tes Lisan"),
                    ("portofolio", "Portofolio"),
                    ("praktek", "Praktek"),
                    ("proyek", "Proyek"),
                    ("uts", "UTS"),
                    ("uas", "UAS"),
                    ("UH", "Ulangan Harian"),
                    ("UTS", "Ujian Tengah Semester"),
                    ("UAS", "Ujian Akhir Semester"),
                    ("Tugas", "Tugas"),
                    ("Proyek", "Proyek (Legacy)"),
                ],
                max_length=50,
            ),
        ),
    ]
