# Generated by Django 5.2.10 on 2026-02-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nisn", models.CharField(max_length=20, unique=True)),
                ("nama", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("kelas", models.CharField(blank=True, max_length=20, null=True)),
                ("program", models.CharField(blank=True, max_length=50, null=True)),
                ("wali_nama", models.CharField(blank=True, max_length=100, null=True)),
                ("wali_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("alamat", models.TextField(blank=True, null=True)),
                ("tanggal_lahir", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Persetujuan"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "pending_registrations",
                "ordering": ["-created_at"],
            },
        ),
    ]
