# Generated by Django 5.2.10 on 2026-01-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kelas",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linked_student_nisn",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadmin"),
                    ("pimpinan", "Pimpinan"),
                    ("guru", "Guru"),
                    ("walisantri", "Walisantri"),
                    ("pendaftar", "Pendaftar"),
                ],
                default="pendaftar",
                max_length=20,
            ),
        ),
    ]
