# Generated by Django 5.2.10 on 2026-01-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_kelas_user_linked_student_nisn_user_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mata_pelajaran",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
