# Generated by Django 5.2.10 on 2026-02-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_mata_pelajaran"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadmin"),
                    ("pimpinan", "Pimpinan"),
                    ("guru", "Guru"),
                    ("bendahara", "Bendahara"),
                    ("walisantri", "Walisantri"),
                    ("pendaftar", "Pendaftar"),
                ],
                default="pendaftar",
                max_length=20,
            ),
        ),
    ]
