# Generated by Django 5.2.10 on 2026-03-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linked_student_nisns",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of NISN for multi-child support, e.g. ['20260001', '20260002']",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadmin"),
                    ("pimpinan", "Pimpinan"),
                    ("guru", "Guru"),
                    ("musyrif", "Musyrif"),
                    ("admin_kelas", "Admin Kelas"),
                    ("bendahara", "Bendahara"),
                    ("walisantri", "Walisantri"),
                    ("adituren", "Adituren/Alumni"),
                    ("pendaftar", "Pendaftar"),
                ],
                default="pendaftar",
                max_length=20,
            ),
        ),
    ]
