# Generated by Django 5.2.10 on 2026-03-11 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_add_roles_and_multi_child"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("kbm", "KBM (Kegiatan Belajar Mengajar)"),
                            ("diniyah", "Diniyah"),
                            ("halaqoh", "Halaqoh Tahfidz/Tahsin"),
                            ("piket", "Piket Harian"),
                            ("wali_kelas", "Wali Kelas"),
                        ],
                        help_text="Jenis penugasan",
                        max_length=20,
                    ),
                ),
                (
                    "kelas",
                    models.CharField(
                        blank=True,
                        help_text="Kelas yang ditugaskan (untuk KBM/Diniyah/Wali Kelas)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "halaqoh_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ID Halaqoh yang ditugaskan (untuk assignment Halaqoh)",
                        null=True,
                    ),
                ),
                (
                    "mata_pelajaran",
                    models.CharField(
                        blank=True,
                        help_text="Mata pelajaran (untuk KBM)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "hari",
                    models.CharField(
                        blank=True,
                        help_text="Hari tugas (untuk piket), format: Senin,Selasa,Rabu",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tahun_ajaran",
                    models.CharField(
                        help_text="Tahun ajaran, format: 2025/2026", max_length=10
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("Ganjil", "Ganjil"), ("Genap", "Genap")],
                        default="Ganjil",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktif"),
                            ("inactive", "Tidak Aktif"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("catatan", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Username admin yang membuat assignment",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Ustadz/Ustadzah yang ditugaskan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "db_table": "user_assignments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "assignment_type"], name="idx_assign_user_type"
                    ),
                    models.Index(
                        fields=["kelas", "assignment_type"],
                        name="idx_assign_kelas_type",
                    ),
                    models.Index(
                        fields=["tahun_ajaran", "semester"], name="idx_assign_periode"
                    ),
                    models.Index(fields=["status"], name="idx_assign_status"),
                ],
                "unique_together": {
                    (
                        "user",
                        "assignment_type",
                        "kelas",
                        "halaqoh_id",
                        "tahun_ajaran",
                        "semester",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create User"),
                            ("update", "Update User"),
                            ("delete", "Delete User"),
                            ("reset_password", "Reset Password"),
                            ("assign", "Assign Role/Task"),
                            ("unassign", "Remove Assignment"),
                            ("activate", "Activate User"),
                            ("deactivate", "Deactivate User"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detail perubahan dalam format JSON",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "target_user",
                    models.ForeignKey(
                        help_text="User yang menjadi target aksi",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User yang melakukan aksi",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "db_table": "user_activities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"], name="idx_activity_user_time"
                    ),
                    models.Index(
                        fields=["action", "timestamp"], name="idx_activity_action_time"
                    ),
                    models.Index(fields=["target_user"], name="idx_activity_target"),
                ],
            },
        ),
    ]
