# Generated by Django 5.2.10 on 2026-04-12 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_rename_admin_kelas_to_wali_kelas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
