# Generated by Django 5.2.10 on 2026-04-24 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('pimpinan', 'Pimpinan'), ('guru', 'Guru'), ('musyrif', 'Musyrif'), ('bk', 'Guru BK'), ('bendahara', 'Bendahara'), ('walisantri', 'Walisantri'), ('adituren', 'Adituren/Alumni'), ('pendaftar', 'Pendaftar')], default='pendaftar', max_length=20),
        ),
        migrations.CreateModel(
            name='CatatanKelas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kelas', models.CharField(help_text='Kelas yang dicatat', max_length=20)),
                ('tanggal', models.DateField(help_text='Tanggal catatan')),
                ('kategori', models.CharField(choices=[('harian', 'Catatan Harian'), ('akademik', 'Akademik'), ('kedisiplinan', 'Kedisiplinan'), ('kegiatan', 'Kegiatan Kelas'), ('lainnya', 'Lainnya')], default='harian', max_length=20)),
                ('judul', models.CharField(help_text='Judul singkat catatan', max_length=200)),
                ('isi', models.TextField(help_text='Isi catatan lengkap')),
                ('tahun_ajaran', models.CharField(help_text='Tahun ajaran, format: 2025/2026', max_length=10)),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], default='Ganjil', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wali_kelas', models.ForeignKey(help_text='Wali Kelas yang membuat catatan', on_delete=django.db.models.deletion.CASCADE, related_name='catatan_kelas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catatan Kelas',
                'verbose_name_plural': 'Catatan Kelas',
                'db_table': 'catatan_kelas',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
