# Generated by Django 4.2.29 on 2026-04-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_catatan_kelas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadmin"),
                    ("admin", "Admin"),
                    ("pimpinan", "Pimpinan"),
                    ("guru", "Guru"),
                    ("musyrif", "Musyrif"),
                    ("bk", "Guru BK"),
                    ("bendahara", "Bendahara"),
                    ("walisantri", "Walisantri"),
                    ("adituren", "Adituren/Alumni"),
                    ("pendaftar", "Pendaftar"),
                ],
                default="pendaftar",
                max_length=20,
            ),
        ),
    ]
