# Generated by Django 5.2.10 on 2026-05-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('kbm', 'KBM (Kegiatan Belajar Mengajar)'), ('diniyah', 'Diniyah'), ('halaqoh', 'Halaqoh Tahfidz/Tahsin'), ('piket', 'Piket Harian'), ('wali_kelas', 'Wali Kelas'), ('hafalan', 'Input Hafalan')], help_text='Jenis penugasan', max_length=20),
        ),
    ]
