# Generated by Django 4.2.30 on 2026-05-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('admin_santri', 'Admin Santri'), ('pimpinan', 'Pimpinan'), ('guru', 'Guru'), ('bk', 'Guru BK'), ('bendahara', 'Bendahara'), ('walisantri', 'Walisantri'), ('adituren', 'Adituren/Alumni')], default='guru', max_length=20),
        ),
    ]
