# Generated by Django 5.2.10 on 2026-01-29 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "students",
            "0002_student_aktif_student_current_hafalan_student_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tanggal", models.DateField()),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("prestasi", "Prestasi"),
                            ("pelanggaran", "Pelanggaran"),
                        ],
                        max_length=20,
                    ),
                ),
                ("evaluator", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("catatan", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="evaluations/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nisn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "evaluations",
                "ordering": ["-created_at"],
            },
        ),
    ]
